server:
  port: 9091
  servlet:
    context-path: /rabbitmq

spring:
  profiles:
    active: @profile.active@
  jackson:
    time-zone: GMT+8

  datasource:
    druid:
      #初始化时创建物理连接的个数
      initialSize: 5
      #最小连接池数量
      minIdle: 1
      #最大连接池数量
      maxActive: 50
      #获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMills: 60000
      #链接保持空闲而不被驱逐的最小时间
      minEvictableIdleTimeMills: 300000
      #用来检测连接是否有效的sql，要求一个查询语句
      validationQuery: select 1 from dual
      #建议配置为true，不影响性能，并且保证安全性，申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      poolPreparedStatements: false
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      maxPoolPreparedStatementPerConnectionSize: 50
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: top.inson.rabbitmq.entity
  mapper-locations: classpath:mappers/**/*.xml

mapper:
  mappers: top.inson.rabbitmq.base.ITKBaseMapper

logging:
  config: classpath:logback-black.xml

#rabbitmq消息队列配置
trade:
  queue:
    delayQueue: tree_delay_queue
    delayExchange: tree_delay_exchange
    delayRoutingKey: tree_delay_key

    queueName: tree_queue
    exchangeName: tree_exchange
    routingKey: tree_key


